version: '3.7'

services:
  app:
    build: ./app
    image: mini-loan-app/app:latest
    ports:
      - "8081:8080"
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=aspire123
      - POSTGRES_DB=mini_loan_app
